import 'package:grocery_mart/Core/Constant/Images/Png_Names/Png_Names.dart';
import 'package:grocery_mart/Features/Shop/Domain/Entity/Entity.dart';

final List<CardItemEntity> dummyCardItems = [
  CardItemEntity(
    id: '13',
    imageUrl: ImageName.pulses,
    name: 'Pulses',
    quantity: 3,
    price: 2.70,
    favourite: false,
    productDetail: 'High-protein organic pulses. ',
    nutrition: 'Protein, Fiber, Iron',
    review: 'Great quality!',
    rating: 1,
  ),
  CardItemEntity(
    id: '14',
    imageUrl: ImageName.rice,
    name: 'Rice',
    quantity: 1,
    price: 4.35,
    favourite: true,
    productDetail: 'Finest basmati rice.',
    nutrition: 'Carbs, Protein',
    review: 'Soft and long grains.',
    rating: 4.7,
  ),
  CardItemEntity(
    id: '1',
    imageUrl: ImageName.apple,
    name: 'Apple',
    quantity: 2,
    price: 3.99,
    favourite: true,
    productDetail: 'Fresh and crispy apples.',
    nutrition: 'Fiber, Vitamin C',
    review: 'Very juicy and sweet!',
    rating: 4.5,
  ),
  CardItemEntity(
    id: '2',
    imageUrl: ImageName.bakery,
    name: 'Bakery',
    quantity: 1,
    price: 4.49,
    favourite: false,
    productDetail: 'Freshly baked bread and pastries.',
    nutrition: 'Carbs, Fats',
    review: 'Breads are soft and fresh.',
    rating: 4.2,
  ),
  CardItemEntity(
    id: '3',
    imageUrl: ImageName.banana,
    name: 'Banana',
    quantity: 6,
    price: 2.99,
    favourite: true,
    productDetail: 'Organic ripe bananas.',
    nutrition: 'Potassium, Fiber',
    review: 'Perfect ripeness.',
    rating: 4.8,
  ),
  CardItemEntity(
    id: '4',
    imageUrl: ImageName.beef,
    name: 'Beef',
    quantity: 1,
    price: 12.50,
    favourite: false,
    productDetail: 'Premium quality beef cuts.',
    nutrition: 'Protein, Iron, Zinc',
    review: 'Very tender.',
    rating: 4.4,
  ),
  CardItemEntity(
    id: '5',
    imageUrl: ImageName.bellPepper,
    name: 'Bell Pepper',
    quantity: 3,
    price: 1.79,
    favourite: true,
    productDetail: 'Colorful and crunchy peppers.',
    nutrition: 'Vitamin C, A, Antioxidants',
    review: 'Very fresh.',
    rating: 4.6,
  ),
  CardItemEntity(
    id: '6',
    imageUrl: ImageName.beverage,
    name: 'Beverage',
    quantity: 2,
    price: 5.25,
    favourite: false,
    productDetail: 'Refreshing soft drink pack.',
    nutrition: 'Sugar, Electrolytes',
    review: 'Cool and tasty!',
    rating: 4.1,
  ),
  CardItemEntity(
    id: '7',
    imageUrl: ImageName.chicken,
    name: 'Chicken',
    quantity: 1,
    price: 9.99,
    favourite: true,
    productDetail: 'Lean chicken breast cuts.',
    nutrition: 'Protein, B12',
    review: 'Clean and well-packed.',
    rating: 4.5,
  ),
  CardItemEntity(
    id: '8',
    imageUrl: ImageName.dairy,
    name: 'Dairy',
    quantity: 2,
    price: 4.10,
    favourite: false,
    productDetail: 'Milk, cheese, and yogurt.',
    nutrition: 'Calcium, Vitamin D',
    review: 'Very fresh dairy items.',
    rating: 4.3,
  ),
  CardItemEntity(
    id: '9',
    imageUrl: ImageName.meat,
    name: 'Meat',
    quantity: 1,
    price: 11.20,
    favourite: false,
    productDetail: 'Red meat selection.',
    nutrition: 'Protein, Iron, B12',
    review: 'Good portion sizes.',
    rating: 4.2,
  ),
  CardItemEntity(
    id: '10',
    imageUrl: ImageName.oil,
    name: 'Oil',
    quantity: 1,
    price: 3.60,
    favourite: false,
    productDetail: 'Pure sunflower cooking oil.',
    nutrition: 'Fats, Vitamin E',
    review: 'Great packaging.',
    rating: 4.0,
  ),
  CardItemEntity(
    id: '11',
    imageUrl: ImageName.pulses,
    name: 'Pulses',
    quantity: 1,
    price: 2.70,
    favourite: false,
    productDetail: 'Nutritious lentils and peas.',
    nutrition: 'Fiber, Iron',
    review: 'High quality.',
    rating: 4.1,
  ),
  CardItemEntity(
    id: '12',
    imageUrl: ImageName.rice,
    name: 'Rice',
    quantity: 1,
    price: 4.35,
    favourite: true,
    productDetail: 'Super fine white rice.',
    nutrition: 'Carbohydrates',
    review: 'Very clean and fluffy.',
    rating: 4.6,
  ),
];
